accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', customer_signup, name='signup'),
    path('login/', customer_login, name='login'),
    path('logout/', customer_logout, name='logout'),
   ]

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [

    path('cart/', cart, name='cart'),

]

django_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shops')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('carts/', include('cart.urls', namespace='carts')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model


User = get_user_model()


class CustomerRegistrationForm(forms.ModelForm):
    username = forms.CharField(max_length=10)
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField(label='Email address')
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [

            'first_name',
            'last_name',
            'username',
            'email',
            'password',
            'confirm_password',

        ]


class CustomerLoginForm(forms.Form):
    username = forms.CharField(label='username')
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(CustomerLoginForm, self).clean(*args, **kwargs)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, get_user_model, login, logout
from .forms import CustomerRegistrationForm, CustomerLoginForm


def customer_signup(request):
    next = request.GET.get('next')
    form = CustomerRegistrationForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect('accounts:login')

    context = {
        'form': form,
    }

    return render(request, "accounts/customer_signup.html", context)


def customer_login(request):
    next = request.GET.get('next')
    form = CustomerLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                request.session.set_expiry(1200)
                login(request, user)
                return redirect('/')
    context = {
        'form': form
    }
    return render(request, "accounts/customer_login.html", context)


def customer_logout(request):
    logout(request)
    return redirect('accounts:login')

templates/accounts/customer_login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
 <div class="container ">
<div class="row block-9">
          <div class="col-md-6 order-md-last d-flex">

            <form action="/accounts/login/" method="POST" class="bg-white p-10 login-form">
                {% csrf_token %}
                   {{ form|crispy }}
            </br>
                <input type="submit" value="Login" class="btn btn-primary py-3 px-5">

            </form>


          </div>

        </div>
<p>Dont have a account? <a href="{% url 'accounts:signup' %}">SignUp</a></p>
</div>
{% endblock %}

templates/accounts/customer_signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<div class="row block-9">
          <div class="col-md-12 order-md-last d-flex">
            <form action="/accounts/signup/" method="POST" class="bg-white p-5 contact-form">
                {% csrf_token %}
                   {{ form|crispy }}
            </br>
                <input type="submit" value="SignUp" class="btn btn-primary py-3 px-5">

            </form>

          </div>


        </div>

</div>
{% endblock %}